In [7]:
import pandas as pd
import numpy as np
import requests
import sys

In [2]:
url = 'https://aqicn.org/data-platform/covid19/report/10806-5622c73e/2020'
myfile = requests.get(url)
open('waqi-covid-2020.csv', 'wb').write(myfile.content)

35761881

In [3]:
csv2020_aqi = './waqi-covid-2020.csv'
csv2019q1_aqi = './waqi-covid19-airqualitydata-2019Q1.csv'
csv2019q2_aqi = './waqi-covid19-airqualitydata-2019Q2.csv'
csv2019q3_aqi = './waqi-covid19-airqualitydata-2019Q3.csv'
csv2019q4_aqi = './waqi-covid19-airqualitydata-2019Q4.csv'
csvcountry_alpha2 = './country-alpha2-code.csv'
df_2020 = pd.read_csv(csv2020_aqi,comment='#')
df_2019_q1 = pd.read_csv(csv2019q1_aqi,comment='#')
df_2019_q2 = pd.read_csv(csv2019q2_aqi,comment='#')
df_2019_q3 = pd.read_csv(csv2019q3_aqi,comment='#')
df_2019_q4 = pd.read_csv(csv2019q4_aqi,comment='#')
alldf = []
alldf.append(df_2019_q1)
alldf.append(df_2019_q2)
alldf.append(df_2019_q3)
alldf.append(df_2019_q4)
country_alpha2 = pd.read_csv(csvcountry_alpha2,comment='#')

In [11]:
def join_df_bykey(leftdf,rightdf, leftkey,rightkey):
    newdf = leftdf.join(rightdf.set_index(rightkey), on=leftkey, how='left', lsuffix='_left', rsuffix='_right')
    return newdf
country_1 = "Australia"
city_1 = "Sydney"
pollutant_1 = "no2"
# country_1 = sys.argv[1]
# city_1 = sys.argv[2]
# pollutant_1 = sys.argv[3]
df_2020_fullc = join_df_bykey(df_2020, country_alpha2, 'Country','alpha-2-code')
for x_df in alldf:
    re_df = join_df_bykey(x_df, country_alpha2, 'Country','alpha-2-code')
    df_2020_fullc=df_2020_fullc.append(re_df,ignore_index=True)

df_selected = df_2020_fullc.loc[(df_2020_fullc['Country_right'] == country_1) & (df_2020_fullc['City'] == city_1) &(df_2020_fullc['Specie'] == pollutant_1)]
#website provide country, city (optional),pollutant,year(optional),  value : average 
#and df_2020_fullc['City'] == city_1
df_selected.sort_values(by=['Date'],ascending=False,inplace=True)
# df_selected.to_csv('./user_requested_data/{0}_{1}_{2}.csv'.format(country_1,city_1,pollutant_1))

df_selected

C:\Users\Nick Wang\Anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Date,Country_left,City,Specie,count,min,max,median,variance,Country_right
81154,2020-04-26,AU,Sydney,no2,28,1.9,21.3,9.3,309.49,Australia
81124,2020-04-25,AU,Sydney,no2,151,1.0,31.5,8.4,490.98,Australia
81163,2020-04-24,AU,Sydney,no2,159,1.0,33.4,14.9,853.86,Australia
81147,2020-04-23,AU,Sydney,no2,140,1.0,32.5,15.8,602.71,Australia
81182,2020-04-22,AU,Sydney,no2,134,1.0,33.4,13.9,828.28,Australia
...,...,...,...,...,...,...,...,...,...,...
1004298,2019-01-04,AU,Sydney,no2,141,1.0,26.9,5.6,216.15,Australia
1004285,2019-01-03,AU,Sydney,no2,121,1.0,12.1,2.8,41.48,Australia
1004326,2019-01-02,AU,Sydney,no2,148,1.0,21.3,4.7,117.75,Australia
1004319,2019-01-01,AU,Sydney,no2,139,1.0,23.2,3.8,143.38,Australia
1004334,2018-12-31,AU,Sydney,no2,154,1.0,20.4,6.5,208.47,Australia

In [13]:
df_2020_fullc

,Date,Country_left,City,Specie,count,min,max,median,variance,Country_right
0,2020-04-05,BR,SÃ£o JosÃ© dos Campos,o3,67,0.9,49.2,15.5,1410.60,Brazil
1,2020-04-17,BR,SÃ£o JosÃ© dos Campos,o3,68,8.6,24.4,17.1,196.74,Brazil
2,2020-01-09,BR,SÃ£o JosÃ© dos Campos,o3,65,0.5,28.9,13.0,549.58,Brazil
3,2020-02-23,BR,SÃ£o JosÃ© dos Campos,o3,47,6.1,20.4,14.3,87.95,Brazil
4,2020-03-07,BR,SÃ£o JosÃ© dos Campos,o3,70,0.5,33.8,13.5,779.16,Brazil
...,...,...,...,...,...,...,...,...,...,...
2838161,2019-11-29,HR,Split,wind-speed,72,0.5,6.9,1.5,15.23,Croatia
2838162,2019-12-07,HR,Split,wind-speed,69,0.2,3.0,1.0,4.68,Croatia
2838163,2019-09-30,HR,Split,wind-speed,72,0.2,3.8,1.8,9.14,Croatia
2838164,2019-12-22,HR,Split,wind-speed,72,2.0,11.5,6.6,65.17,Croatia
2838165,2019-10-31,HR,Split,wind-speed,72,1.5,5.9,3.0,13.45,Croatia

In [20]:
countries = df_2020_fullc.Country_right.unique()
cities = df_2020_fullc.City.unique()
pollutants = df_2020_fullc.Specie.unique()

# for country in countries:
#     df_country = df_2020_fullc.loc[df_2020_fullc['Country_right'] == country]
#     if(not df_country.empty):
#         os.mkdir('./data_divid/{0}'.format(country))

for country in countries:
    for city in cities:
        df_city = df_2020_fullc.loc[(df_2020_fullc['Country_right'] == country) & (df_2020_fullc['City'] == city)]
        path = './data_divid/{0}/{1}'.format(country,city)
        if((not df_city.empty) & (not os.path.exists(path))):
            os.mkdir(path)

# for countryii in countries:
#     for city in cities:
#         for pollutant in pollutants:
#             df_pollutant = df_2020_fullc.loc[(df_2020_fullc['Country_right'] == country) & (df_2020_fullc['City'] == city) & (df_2020_fullc['Specie'] == pollutant)]
#             if(not df_pollutant.empty):
#                 os.mkdir('./data_divid/{0}/{1}/{2}'.format(country,city,pollutant))

KeyboardInterrupt:

In [29]:
from pathlib import Path
for country in countries:
    for city in cities:
        for pollutant in ['no2','pm25']:
            df_pollutant_sorted = df_2020_fullc.loc[(df_2020_fullc['Country_right'] == country) & (df_2020_fullc['City'] == city) & (df_2020_fullc['Specie'] == pollutant)].sort_values(by=['Date'],ascending=False)
            path = './data_divid/{0}/{1}/{2}'.format(country,city,pollutant)
            
            if((not df_pollutant_sorted.empty) ):
                if((not os.path.exists(path))):
                    path_real = Path(path)
                    path_real.mkdir(parents=True)
                    df_pollutant_sorted.to_csv('./data_divid/{0}/{1}/{2}/{0}_{1}_{2}.csv'.format(country,city,pollutant))
                else:
                    df_pollutant_sorted.to_csv('./data_divid/{0}/{1}/{2}/{0}_{1}_{2}.csv'.format(country,city,pollutant))

KeyboardInterrupt: